// Code generated by "stringer -type=Color"; DO NOT EDIT.

package server

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ColorUnknown - -1]
	_ = x[ColorMajenta-0]
	_ = x[ColorCyan-1]
	_ = x[ColorYellow-2]
	_ = x[ColorBlue-3]
	_ = x[ColorGreen-4]
	_ = x[ColorRed-5]
	_ = x[ColorWhite-6]
	_ = x[ColorBlack-7]
}

const _Color_name = "ColorUnknownColorMajentaColorCyanColorYellowColorBlueColorGreenColorRedColorWhiteColorBlack"

var _Color_index = [...]uint8{0, 12, 24, 33, 44, 53, 63, 71, 81, 91}

func (i Color) String() string {
	i -= -1
	if i < 0 || i >= Color(len(_Color_index)-1) {
		return "Color(" + strconv.FormatInt(int64(i+-1), 10) + ")"
	}
	return _Color_name[_Color_index[i]:_Color_index[i+1]]
}
